# Generated by Django 2.2.5 on 2019-09-24 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="user name")),
                (
                    "surname",
                    models.CharField(max_length=60, verbose_name="user surname"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_text", models.TextField(verbose_name="post text")),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                (
                    "likes_count",
                    models.IntegerField(default=0, verbose_name="likes count"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.User"
                    ),
                ),
            ],
        ),
    ]
