# Generated by Django 2.2.5 on 2019-09-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blog", "0001_initial")]

    operations = [
        migrations.RenameField(model_name="post", old_name="post", new_name="user"),
        migrations.AddField(
            model_name="post",
            name="post_title",
            field=models.CharField(
                default="", max_length=150, verbose_name="post title"
            ),
            preserve_default=False,
        ),
    ]
