# Generated by Django 2.2.5 on 2019-09-25 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blog", "0003_auto_20190925_1548")]

    operations = [
        migrations.AddField(
            model_name="like",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        )
    ]
